### ISSUE TITLE
could your share the wheel of pytorch for TX2?

### ISSUE THREAD

**Issue by perry0418** [ShreyasSkandanS/nvidia_tx_utils#1]
sorry to disturb you, I follow your script to install the pytorch from the source, and it didn't work out. could you share your pytorch wheel with python3.5 for TX2 ?

**Comment by ShreyasSkandan** [comment]
This is super late, but I have a pip wheel for Python3.5 and PyTorch1.0.0 in this repo. You can find it in the wheels folder.
