### ISSUE TITLE
No module named setuptool

### ISSUE THREAD

**Issue by naruto1980** [ShreyasSkandanS/nvidia_tx_utils#2]
Hi,
I have a question regarding building PyTorch
After step:
`sudo pip3 install -U setuptools`
I got "`Successfully installed setuptools-40.8.0`"

But not sure when running 
`python setup.py build_deps`
I got 
 `File "setup.py", line 145, in <module> 
    from setuptools import setup, Extension, distutils, Command, find_packages 
ImportError: No module named setuptools`

Please let me know how to fix it.

**Comment by ShreyasSkandan** [comment]
Is your default python version Python3 ?

Do you get the same error when you try python3 setup.py build_deps ?

**Comment by naruto1980** [comment]
By accident, I installed both Python 3.5 and Python 3.7.

I got below messsage when running `python3 setup.py build_deps`
```
Building wheel torch-1.1.0a0+221eddd
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
      or: setup.py --help [cmd1 cmd2 ...]
      or: setup.py --help-commands
      or: setup.py cmd --help

error: invalid command 'build_deps'
```

**Comment by ShreyasSkandan** [comment]
I would recommend removing one of the two Python3.X or using some kind of virtual environment for your other Python version. I believe build_deps needs to be installed and linked to the version of Python3 that you are defaulting to.

**Comment by naruto1980** [comment]
Hi,
Do you have any idea how to install build_deps. I tried to search around but I can only find build-deps nothing relating to build_deps
Thank you so much for your effort.

**Comment by ShreyasSkandan** [comment]
Hi, please try just installing the pip wheel in the wheel folder of this repository. It should be smooth and painless.
